Feature/db configure
michel1n0/dw-wallet-service pull request #4
Opened 2023-08-27 22:46 UTC by michel1n0

set new uri mongodb connection

2023-08-27 22:57 UTC, oliveraluiss11 requested changes
Corregir porfavor :D

2023-08-27 22:57 UTC, oliveraluiss11 commented on src/main/resources/application.yml
> +      uri:  mongodb+srv://fpaucarcaceres:XUWOIlmJ07eKGvEQ@digitalwallet.cxokdkr.mongodb.net/dw-wallet?retryWrites=true&w=majority
Debería ser al final service.
Hay dos convenciones:
- digitalwallet-{nombremicroservicio}-service
- dw-{nombremicroservicio}-service

2023-08-27 23:23 UTC, michel1n0 commented on src/main/resources/application.yml
> +      uri:  mongodb+srv://fpaucarcaceres:XUWOIlmJ07eKGvEQ@digitalwallet.cxokdkr.mongodb.net/dw-wallet?retryWrites=true&w=majority
Consulta, lo que me indicas es para el nombre del repositorio o para el nombre de la BD?

2023-08-28 00:15 UTC, oliveraluiss11 requested changes
Corregir :D

2023-08-28 00:15 UTC, oliveraluiss11 commented on src/main/resources/application.yml
> +      uri:  mongodb+srv://fpaucarcaceres:XUWOIlmJ07eKGvEQ@digitalwallet.cxokdkr.mongodb.net/dw-wallet?retryWrites=true&w=majority
para ambos casos :D

2023-08-28 00:16 UTC, merged